# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 614)
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:#22222e;")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockOptions(
            QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Employeedatabasetext = QtWidgets.QLabel(self.centralwidget)
        self.Employeedatabasetext.setGeometry(QtCore.QRect(290, 10, 301, 30))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(24)
        font.setItalic(False)
        self.Employeedatabasetext.setFont(font)
        self.Employeedatabasetext.setStyleSheet("color:#f08080")
        self.Employeedatabasetext.setObjectName("Employeedatabasetext")
        self.NameSurname = QtWidgets.QLineEdit(self.centralwidget)
        self.NameSurname.setGeometry(QtCore.QRect(30, 60, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        self.NameSurname.setFont(font)
        self.NameSurname.setStyleSheet(
            "background-color: #22222e;\n"
            "border:2px solid #f08080;\n"
            "border-radius:10;\n"
            "color:white"
        )
        self.NameSurname.setText("")
        self.NameSurname.setAlignment(QtCore.Qt.AlignCenter)
        self.NameSurname.setObjectName("NameSurname")
        self.YesCar = QtWidgets.QCheckBox(self.centralwidget)
        self.YesCar.setGeometry(QtCore.QRect(40, 320, 43, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.YesCar.setFont(font)
        self.YesCar.setStyleSheet("color:white")
        self.YesCar.setObjectName("YesCar")
        self.Addaperson = QtWidgets.QPushButton(self.centralwidget)
        self.Addaperson.setGeometry(QtCore.QRect(40, 510, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Addaperson.setFont(font)
        self.Addaperson.setStyleSheet(
            "QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 10px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 80px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }\n"
            "\n"
            " QPushButton:flat {\n"
            "     border: none; /* для плоской кнопки границы нет */\n"
            " }\n"
            "\n"
            " QPushButton:default {\n"
            "     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
            " }"
        )
        self.Addaperson.setObjectName("Addaperson")
        self.Deleteaperson = QtWidgets.QPushButton(self.centralwidget)
        self.Deleteaperson.setGeometry(QtCore.QRect(550, 470, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.Deleteaperson.setFont(font)
        self.Deleteaperson.setStyleSheet(
            "QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 10px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 80px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }\n"
            "\n"
            " QPushButton:flat {\n"
            "     border: none; /* для плоской кнопки границы нет */\n"
            " }\n"
            "\n"
            " QPushButton:default {\n"
            "     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
            " }"
        )
        self.Deleteaperson.setObjectName("Deleteaperson")
        self.Doyouhaveacartext = QtWidgets.QLabel(self.centralwidget)
        self.Doyouhaveacartext.setGeometry(QtCore.QRect(40, 290, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(10)
        font.setItalic(False)
        self.Doyouhaveacartext.setFont(font)
        self.Doyouhaveacartext.setStyleSheet("color:#f08080")
        self.Doyouhaveacartext.setObjectName("Doyouhaveacartext")
        self.ProgrammingLanguagetext = QtWidgets.QLabel(self.centralwidget)
        self.ProgrammingLanguagetext.setGeometry(QtCore.QRect(40, 350, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(10)
        font.setItalic(False)
        self.ProgrammingLanguagetext.setFont(font)
        self.ProgrammingLanguagetext.setStyleSheet("color:#f08080")
        self.ProgrammingLanguagetext.setObjectName("ProgrammingLanguagetext")
        self.NoCar = QtWidgets.QCheckBox(self.centralwidget)
        self.NoCar.setGeometry(QtCore.QRect(110, 320, 38, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NoCar.setFont(font)
        self.NoCar.setStyleSheet("color:white")
        self.NoCar.setObjectName("NoCar")
        self.Addanewemployeetext = QtWidgets.QLabel(self.centralwidget)
        self.Addanewemployeetext.setGeometry(QtCore.QRect(30, 20, 183, 24))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(14)
        font.setItalic(False)
        self.Addanewemployeetext.setFont(font)
        self.Addanewemployeetext.setStyleSheet("color:#f08080")
        self.Addanewemployeetext.setObjectName("Addanewemployeetext")
        self.Height = QtWidgets.QLineEdit(self.centralwidget)
        self.Height.setGeometry(QtCore.QRect(30, 190, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        self.Height.setFont(font)
        self.Height.setStyleSheet(
            "background-color: #22222e;\n"
            "border:2px solid #f08080;\n"
            "border-radius:10;\n"
            "color:white"
        )
        self.Height.setText("")
        self.Height.setAlignment(QtCore.Qt.AlignCenter)
        self.Height.setObjectName("Height")
        self.Weight = QtWidgets.QLineEdit(self.centralwidget)
        self.Weight.setGeometry(QtCore.QRect(30, 230, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        self.Weight.setFont(font)
        self.Weight.setStyleSheet(
            "background-color: #22222e;\n"
            "border:2px solid #f08080;\n"
            "border-radius:10;\n"
            "color:white"
        )
        self.Weight.setText("")
        self.Weight.setAlignment(QtCore.Qt.AlignCenter)
        self.Weight.setObjectName("Weight")
        self.Deleteanemployeetext = QtWidgets.QLabel(self.centralwidget)
        self.Deleteanemployeetext.setGeometry(QtCore.QRect(550, 510, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(14)
        font.setItalic(False)
        self.Deleteanemployeetext.setFont(font)
        self.Deleteanemployeetext.setStyleSheet("color:#f08080")
        self.Deleteanemployeetext.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.Deleteanemployeetext.setObjectName("Deleteanemployeetext")
        self.Search = QtWidgets.QPushButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(300, 510, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(10)
        self.Search.setFont(font)
        self.Search.setStyleSheet(
            "QPushButton {\n"
            "     border: 2px solid #8f8f91;\n"
            "     border-radius: 10px;\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
            "     min-width: 80px;\n"
            " }\n"
            "\n"
            " QPushButton:pressed {\n"
            "     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
            "                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
            " }\n"
            "\n"
            " QPushButton:flat {\n"
            "     border: none; /* для плоской кнопки границы нет */\n"
            " }\n"
            "\n"
            " QPushButton:default {\n"
            "     border-color: navy; /* делаем кнопку по умолчанию выпуклой */\n"
            " }"
        )
        self.Search.setObjectName("Search")
        self.Employeesearch = QtWidgets.QLineEdit(self.centralwidget)
        self.Employeesearch.setGeometry(QtCore.QRect(290, 470, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(12)
        self.Employeesearch.setFont(font)
        self.Employeesearch.setStyleSheet(
            "background-color: #22222e;\n"
            "border:2px solid #f08080;\n"
            "border-radius:10;\n"
            "color:white"
        )
        self.Employeesearch.setText("")
        self.Employeesearch.setAlignment(QtCore.Qt.AlignCenter)
        self.Employeesearch.setObjectName("Employeesearch")
        self.Datebirthday = QtWidgets.QDateEdit(self.centralwidget)
        self.Datebirthday.setGeometry(QtCore.QRect(30, 150, 221, 22))
        self.Datebirthday.setStyleSheet(
            "background-color: #22222e;\n" "border:2px solid #f08080;\n" "color:white"
        )
        self.Datebirthday.setCalendarPopup(True)
        self.Datebirthday.setDate(QtCore.QDate(2009, 1, 2))
        self.Datebirthday.setObjectName("Datebirthday")
        self.Addabirhdaytext = QtWidgets.QLabel(self.centralwidget)
        self.Addabirhdaytext.setGeometry(QtCore.QRect(30, 110, 128, 24))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(14)
        font.setItalic(False)
        self.Addabirhdaytext.setFont(font)
        self.Addabirhdaytext.setStyleSheet("color:#f08080")
        self.Addabirhdaytext.setObjectName("Addabirhdaytext")
        self.table_data = QtWidgets.QTableWidget(self.centralwidget)
        self.table_data.setEnabled(True)
        self.table_data.setGeometry(QtCore.QRect(290, 50, 645, 401))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.table_data.setFont(font)
        self.table_data.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "selection-background-color: rgb(82, 206, 225);\n"
            "selection-color: rgb(0, 0, 0);"
        )
        self.table_data.setRowCount(0)
        self.table_data.setColumnCount(6)
        self.table_data.setObjectName("table_data")
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_data.setHorizontalHeaderItem(5, item)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 390, 151, 71))
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.Cplusplus = QtWidgets.QRadioButton(self.groupBox)
        self.Cplusplus.setGeometry(QtCore.QRect(10, 10, 47, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cplusplus.setFont(font)
        self.Cplusplus.setStyleSheet("color:white")
        self.Cplusplus.setObjectName("Cplusplus")
        self.Delphi = QtWidgets.QRadioButton(self.groupBox)
        self.Delphi.setGeometry(QtCore.QRect(10, 40, 58, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Delphi.setFont(font)
        self.Delphi.setStyleSheet("color:white")
        self.Delphi.setObjectName("Delphi")
        self.Csharp = QtWidgets.QRadioButton(self.groupBox)
        self.Csharp.setGeometry(QtCore.QRect(80, 10, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Csharp.setFont(font)
        self.Csharp.setStyleSheet("color:white")
        self.Csharp.setObjectName("Csharp")
        self.Python = QtWidgets.QRadioButton(self.groupBox)
        self.Python.setGeometry(QtCore.QRect(80, 40, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Python.setFont(font)
        self.Python.setStyleSheet("color:white")
        self.Python.setObjectName("Python")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataBase"))
        self.Employeedatabasetext.setText(_translate("MainWindow", "Employee database"))
        self.YesCar.setText(_translate("MainWindow", "Yes"))
        self.Addaperson.setText(_translate("MainWindow", "Add a person"))
        self.Deleteaperson.setText(_translate("MainWindow", "Delete a person"))
        self.Doyouhaveacartext.setText(_translate("MainWindow", "Do you have a car ?"))
        self.ProgrammingLanguagetext.setText(
            _translate("MainWindow", "Programming language?")
        )
        self.NoCar.setText(_translate("MainWindow", "No"))
        self.Addanewemployeetext.setText(_translate("MainWindow", "Add a new employee"))
        self.Deleteanemployeetext.setText(
            _translate("MainWindow", 'Click index and "delete employee"')
        )
        self.Search.setText(_translate("MainWindow", "Search"))
        self.Addabirhdaytext.setText(_translate("MainWindow", "Add a birthday"))
        item = self.table_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name"))
        item = self.table_data.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "birhtday"))
        item = self.table_data.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "heihgt"))
        item = self.table_data.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "weihgt"))
        item = self.table_data.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "car"))
        item = self.table_data.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "languages"))
        self.Cplusplus.setText(_translate("MainWindow", "C++"))
        self.Delphi.setText(_translate("MainWindow", "Delphi"))
        self.Csharp.setText(_translate("MainWindow", "C#"))
        self.Python.setText(_translate("MainWindow", "Python"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
